import {addQuestion,makeGroup,makePassage,renumber,type Draft,type QuestionType} from '../shared/reading';
export function fixture(types:QuestionType[],start=1,count:number|number[]=3):Draft{
 const d=makePassage(),p=d.content;p.title='Community gardens in growing cities';p.description='How shared green spaces bring neighbours together.';p.label='READING PASSAGE';p.leadIn='You should spend about 20 minutes on this passage.';p.sections=[
  {id:'sec_a',label:'A',blocks:[{id:'blk_a',kind:'paragraph',text:'Community gardens give residents a place to grow vegetables and meet neighbours. On a former car park near the town centre, families now share small plots and learn practical skills from one another. Volunteers collect rainwater in a covered tank. The water is used on dry days, so the group does not need to draw as much from the public supply. Even people who do not have a plot often visit to talk or help with planting.'}]},
  {id:'sec_b',label:'B',blocks:[{id:'blk_b',kind:'paragraph',text:'The gardens are free to join. Local councils provide soil and simple tools, while members care for the plants. Each Saturday, experienced gardeners offer short lessons for beginners. They show children how seeds develop and explain why insects are important to healthy soil. The lessons have become popular with nearby schools, although attendance is voluntary and no special equipment is required.'}]},
  {id:'sec_c',label:'C',blocks:[{id:'blk_c',kind:'paragraph',text:'Shared spaces can also present difficulties. During a long dry period, members had to agree on how much water each plot could use. A small committee proposed a rota, and the gardeners voted for it at a monthly meeting. The new plan reduced waste without preventing anyone from growing crops. Organisers say that clear rules are useful, but regular conversations matter just as much.'}]},
  {id:'sec_d',label:'D',blocks:[{id:'blk_d',kind:'paragraph',text:'Researchers studying the project observed that people who visited regularly reported knowing more of their neighbours. They cautioned that the survey was small and could not prove that gardening alone caused the change. Nevertheless, the project has encouraged other districts to consider similar spaces. Those districts are examining access to land, long term maintenance costs and the needs of local residents.'}]},
  {id:'sec_e',label:'E',blocks:[{id:'blk_e',kind:'paragraph',text:'The next stage will depend on feedback from residents. The council plans to ask both members and non-members which facilities would be most useful. Suggestions already include wider paths, additional seating and a place to store tools. Organisers hope that a design shaped by the community will be easier to maintain and welcoming to visitors of all ages.'}]}
 ];
 for(const [typeIndex,type] of types.entries()){const groupCount=Array.isArray(count)?count[typeIndex]:count;const g=makeGroup(type,start);for(let i=1;i<groupCount;i++)addQuestion(g,start+i);g.instructionBlocks=[{kind:'instruction',text:`Answer the questions about community gardens.`},{kind:'answer_format',text:type.endsWith('_text')?'Write ONE WORD ONLY.':'Choose the correct answer.'}];if(type==='matching_information'||type==='matching_features')g.instructionBlocks.push({kind:'note',text:'NB You may use any letter more than once.'});
  if(g.options)g.options=[{id:'A',text:'community gardens'},{id:'B',text:'covered tank'},{id:'C',text:'local councils'},{id:'D',text:'unused option'}];
  g.questions.forEach((q,i)=>{q.prompt=type==='sentence_completion'?`The gardens are [[gap]] to join.`:type==='multiple_choice_multiple'?'Which TWO benefits are mentioned?':`Community gardens help residents ${i===0?'grow vegetables':'meet neighbours'}.`;if(type==='matching_headings')q.targetSectionId=['sec_a','sec_b','sec_c','sec_d','sec_e'][i%5];if(type==='multiple_choice_single')q.options=[{id:'A',text:'Grow vegetables'},{id:'B',text:'Buy books'},{id:'C',text:'Watch films'}];d.answerKey.answers.push({questionId:q.id,acceptedAnswers:[type==='true_false_not_given'?'TRUE':type==='yes_no_not_given'?'YES':type==='multiple_choice_multiple'?['A','B','C','D','E'][i]:type==='matching_headings'?['i','ii','iii','iv','v'][i%5]:type==='short_answer'||type==='sentence_completion'||type.endsWith('_text')?'free':'A'],explanation:'The passage states the relevant information directly.',evidence:[{sectionId:'sec_a',blockId:'blk_a',quote:'Community gardens give residents a place to grow vegetables and meet neighbours.'}]});});
  if(type==='multiple_choice_multiple'){g.settings={selectionCount:groupCount,scoring:'unordered_set'};}
  if(type==='matching_headings'){g.options=[{id:'i',text:'A place to meet and grow'},{id:'ii',text:'Learning from experienced gardeners'},{id:'iii',text:'Solving a shared resource problem'},{id:'iv',text:'Research and its limits'},{id:'v',text:'Plans shaped by residents'},{id:'vi',text:'An unrelated transport project'},{id:'vii',text:'The history of a building'}];}
  if(type==='diagram_completion_text'&&g.content.kind==='diagram'){g.content.assetId='asset_demo';g.content.alt='Diagram of a rainwater tank';g.content.title='Rainwater system';g.content.anchors.forEach((a,i)=>{a.xPercent=73;a.yPercent=12+i*18});}
  if(g.content.kind==='rich_text_with_gaps'||g.content.kind==='notes'){g.content.title=type.startsWith('note')?'Garden notes':'Garden summary';g.content.blocks=g.questions.map((q,i)=>({kind:type.startsWith('note')?'bullet':'paragraph',parts:[{kind:'text',text:`Fact ${i+1}: gardens are `},{kind:'gap',questionId:q.id},{kind:'text',text:' for residents.'}]}));}
  if(g.content.kind==='table'){g.content.title='Garden facts';g.content.rows=[[{isHeader:true,parts:[{kind:'text',text:'Topic'}]},{isHeader:true,parts:[{kind:'text',text:'Answer'}]}],...g.questions.map((q,i)=>[{parts:[{kind:'text' as const,text:`Fact ${i+1}`}]},{parts:[{kind:'gap' as const,questionId:q.id}]}])];}
  if(g.content.kind==='flowchart'){g.content.title='Garden process';g.content.steps=g.questions.map((q,i)=>({id:`step_${i+1}`,parts:[{kind:'text' as const,text:'Step: '},{kind:'gap' as const,questionId:q.id}],nextStepIds:i<groupCount-1?[`step_${i+2}`]:[]}));}
  p.questionGroups.push(g);start+=groupCount;
 }
 renumber([p],p.questionGroups[0]?.questions[0]?.number??1);return d;
}
