import {fixture} from './fixtures';
import {TYPES,type Draft} from '../shared/reading';
const root=process.env.TEST_API??'http://127.0.0.1:3001/api';const token=process.env.READING_ADMIN_TOKEN||'local-reading-admin';
async function request(path:string,method='GET',body?:unknown,admin=true){const r=await fetch(root+path,{method,headers:{...(admin?{'x-admin-token':token}:{}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const value=await r.json();if(!r.ok)throw new Error(`${method} ${path}: ${r.status} ${JSON.stringify(value)}`);return value;}
const check=(condition:unknown,message:string)=>{if(!condition)throw new Error(message)};
async function createSavePublish(d:Draft){const created=await request('/admin/passages','POST',{});d.content.passageVersionId=created.id;d.answerKey.passageVersionId=created.id;const saved=await request(`/admin/passages/${created.id}/draft`,'PATCH',{revision:created.revision,...d});const reloaded=await request(`/admin/passages/${created.id}/draft`);check(JSON.stringify(saved.content)===JSON.stringify(reloaded.content),'Reload lost content');const validation=await request(`/admin/passages/${created.id}/validate`,'POST',{});check(validation.valid,`Validation failed: ${JSON.stringify(validation.issues)}`);await request(`/admin/passages/${created.id}/publish`,'POST',{});return created.id as string;}
async function main(){const run=Date.now();let done=0;
 for(const type of TYPES){const d=fixture([type],1,type==='multiple_choice_multiple'?2:3);const id=await createSavePublish(d);check(!!id,`No ID for ${type}`);done++;console.log(`PASS ${type}: create/save/reload/validate/publish`);}
 const single=fixture(['true_false_not_given','summary_completion_word_box'],1,[7,4]);const singleId=await createSavePublish(single);const ex=await request('/admin/exercises','POST',{slug:`smoke-single-${run}`,title:single.content.title,description:single.content.description,passageVersionId:singleId,topicIds:['topic_environment']});const exVal=await request(`/admin/exercises/${ex.id}/validate`,'POST',{});check(exVal.valid,'Single exercise validation failed');await request(`/admin/exercises/${ex.id}/publish`,'POST',{});const publicEx=await request(`/reading/exercises/${ex.slug}`,'GET',undefined,false);check(publicEx.passage.questionGroups[0].questions.length===7,'Single seven questions lost');check(!JSON.stringify(publicEx).includes('acceptedAnswers')&&!JSON.stringify(publicEx).includes('explanation')&&!JSON.stringify(publicEx).includes('evidence'),'Answer key leaked in public exercise');const review=await request(`/reading/exercises/${ex.slug}/submit`,'POST',{answers:{}},false);check(review.answerKeys[0].answers.length===11,'Review key not returned after submit');check(review.grade.total===11&&review.grade.unanswered===11,'Blank attempt grade incorrect');const filled=Object.fromEntries(single.answerKey.answers.map(a=>[a.questionId,a.acceptedAnswers[0]]));const scored=await request(`/reading/exercises/${ex.slug}/submit`,'POST',{answers:filled},false);check(scored.grade.correct===11&&scored.grade.total===11,'Correct answers not graded');const list=await request('/reading/exercises?topic=environment&q=Community&page=1','GET',undefined,false);check(list.items.some((x:{id:string})=>x.id===ex.id),'Topic filter failed');console.log('PASS single passage: 7 TF/NG + 4 word-box gaps, topic filter, public safe response, review after submit');
 const ids:string[]=[];let n=1;for(const types of [['true_false_not_given','multiple_choice_single'],['matching_information','short_answer'],['summary_completion_text','flowchart_completion_text']] as const){const d=fixture([...types],n,2);ids.push(await createSavePublish(d));n+=4;}const test=await request('/admin/tests','POST',{slug:`smoke-test-${run}`,title:'Smoke full test',description:'Three passages',timeLimitMinutes:60,passageVersionIds:ids});const tv=await request(`/admin/tests/${test.id}/validate`,'POST',{});check(tv.valid,`Full test invalid: ${JSON.stringify(tv.issues)}`);await request(`/admin/tests/${test.id}/publish`,'POST',{});const publicTest=await request(`/reading/tests/${test.slug}`,'GET',undefined,false);check(publicTest.testPassages.length===3,'Full test missing passage');check(!JSON.stringify(publicTest).includes('acceptedAnswers'),'Answer key leaked in public test');console.log('PASS full test: 3 passages, contiguous numbering, safe public response');console.log(`TOTAL: ${done} question types + single + full test`);
}
main().catch(e=>{console.error(e);process.exitCode=1});
