import {chromium} from 'playwright';
const browser=await chromium.launch({headless:true,executablePath:'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1365,height:900}});await context.addInitScript(()=>sessionStorage.setItem('reading-admin-token','local-reading-admin'));const page=await context.newPage();
const root='http://127.0.0.1:5173';
try{
 await page.goto(`${root}/admin/reading`);await page.getByRole('button',{name:'+ Tạo 1 passage'}).click();await page.locator('.editor-main').waitFor();const url=page.url();
 await page.getByRole('button',{name:'Bài đọc'}).click();await page.getByLabel('Title',{exact:true}).fill('UI workflow sample');await page.getByLabel('Description dưới title').fill('A passage entered through the admin form.');await page.locator('.block-editor textarea').fill('A community garden gives neighbours space to grow food together.');
 await page.getByRole('button',{name:'Nhóm câu hỏi'}).click();await page.getByRole('button',{name:'+ Thêm nhóm'}).click();await page.getByLabel('Instruction').fill('Choose TRUE, FALSE or NOT GIVEN.');await page.getByLabel('Statement').fill('Neighbours can grow food together.');await page.getByRole('button',{name:'Đáp án & giải thích'}).click();await page.getByLabel('Đáp án đúng').selectOption('TRUE');await page.getByLabel('Giải thích riêng').fill('The passage says they grow food together.');await page.getByRole('button',{name:'Lưu',exact:true}).click();await page.waitForTimeout(500);await page.reload();await page.getByRole('button',{name:'Bài đọc'}).click();if(await page.getByLabel('Title',{exact:true}).inputValue()!=='UI workflow sample')throw Error('Reload lost title');
 await page.getByRole('button',{name:'Preview ↗'}).click();await page.locator('.question-panel').waitFor();if(!(await page.locator('.passage-body h1').textContent())?.includes('UI workflow sample'))throw Error('Single draft preview missing title');await page.goto(url);await page.locator('.editor-main').waitFor();await page.getByRole('button',{name:'Kiểm tra & xuất bản'}).click();await page.getByRole('button',{name:'Kiểm tra',exact:true}).click();await page.waitForTimeout(300);const issueCount=await page.locator('.issue').count();if(issueCount)throw Error(`Validation returned ${issueCount} issues: ${await page.locator('.issue').allTextContents()}`);await page.getByRole('button',{name:'Xuất bản passage'}).click();await page.waitForTimeout(300);if(!(await page.locator('.status.published').count()))throw Error('Passage was not published');
 await page.goto(url);await page.locator('.editor-main').waitFor();console.log('PASS UI passage: create → edit → save → reload → preview → validate → publish');
 await page.goto(`${root}/reading/preview/test/sample-reading-test`);await page.locator('.passage-tabs').waitFor();await page.locator('.passage-tabs button').nth(1).click();if(!(await page.locator('.passage-body h1').textContent())?.includes('Shared libraries'))throw Error('Passage navigation failed');await page.locator('.passage-tabs button').nth(2).click();console.log('PASS UI full test preview: Passage 1/2/3 navigation');
 const existing=await fetch('http://127.0.0.1:3001/api/admin/tests',{headers:{'x-admin-token':'local-reading-admin'}}).then(r=>r.json()) as {slug:string;testPassages:{passageVersionId:string}[]}[];const sample=existing.find(x=>x.slug==='sample-reading-test');if(!sample)throw Error('Seed test missing');
 await page.goto(`${root}/admin/reading`);await page.getByRole('button',{name:'Full test · 3 passages'}).click();await page.getByRole('button',{name:'+ Tạo full test'}).click();await page.getByLabel('Title',{exact:true}).fill('UI full test workflow');await page.getByLabel('Description').fill('Three passages selected in the admin wizard.');await page.getByRole('button',{name:'Lưu',exact:true}).click();for(const [i,x] of sample.testPassages.entries()){await page.getByLabel('Chọn passage version').nth(i).selectOption(x.passageVersionId);await page.waitForTimeout(300)}const fullUrl=page.url();await page.reload();await page.locator('.test-slot').first().waitFor();for(const [i,x] of sample.testPassages.entries())if(await page.getByLabel('Chọn passage version').nth(i).inputValue()!==x.passageVersionId)throw Error('Full test reload lost passage');await page.locator('.editor-sidebar a[href*="/preview/test/"]').click();await page.locator('.passage-tabs').waitFor();if(await page.locator('.passage-tabs button').count()!==3)throw Error('Full test draft preview missing passages');await page.goto(fullUrl);await page.locator('.test-slot').first().waitFor();await page.getByRole('button',{name:'Kiểm tra',exact:true}).click();await page.waitForTimeout(250);if(await page.locator('.issue').count())throw Error(`Full test UI validation: ${await page.locator('.issue').allTextContents()}`);await page.getByRole('button',{name:'Xuất bản',exact:true}).click();await page.waitForTimeout(300);if(!(await page.locator('.status.published').count()))throw Error('Full test UI publish failed');console.log('PASS UI full test: create → choose 3 passages → save → reload → preview → validate → publish');
 await page.goto(`${root}/reading/preview/passage/community-gardens`);await page.locator('.question-panel').waitFor();if(await page.locator('.review-list').count())throw Error('Review visible before submit');await page.evaluate(()=>{const p=document.querySelector('.passage-body [data-block]')!;const node=p.firstChild!;const range=document.createRange();range.setStart(node,0);range.setEnd(node,Math.min(12,node.textContent!.length));const selection=window.getSelection()!;selection.removeAllRanges();selection.addRange(range)});await page.getByRole('button',{name:'Highlight'}).click();await page.locator('.passage-body mark').waitFor();console.log('PASS public highlight selection');await page.getByRole('button',{name:'Nộp bài'}).click();await page.locator('.review-list').waitFor();await page.locator('.grade-banner').waitFor();await page.locator('.review-list summary').first().click();await page.getByRole('button',{name:'Xem vị trí'}).first().click();await page.locator('mark').waitFor();console.log('PASS public review: answer key fetched after submit; evidence jump highlights quote');
 const samples=await fetch('http://127.0.0.1:3001/api/admin/exercises',{headers:{'x-admin-token':'local-reading-admin'}}).then(r=>r.json()) as {slug:string;passage_version_id:string}[];const published=samples.find(x=>x.slug==='community-gardens');if(!published)throw Error('Published sample missing');const publishedUrl=`${root}/admin/reading/passages/${published.passage_version_id}/edit`;await page.goto(publishedUrl);await page.locator('.editor-main').waitFor();if(await page.getByRole('button',{name:'Lưu',exact:true}).count())throw Error('Published passage still offers Save');await page.getByRole('button',{name:'Preview ↗'}).click();await page.locator('.preview-shell').waitFor();if(!page.url().includes('/preview/passage/'))throw Error('Published preview did not open');await page.locator('.choice-three button').first().click();await page.getByRole('button',{name:'Nộp bài'}).click();await page.locator('.grade-banner').waitFor();if(!(await page.locator('.grade-banner').textContent())?.includes('Kết quả:'))throw Error('Admin preview grading failed');await page.goto(publishedUrl);await page.getByRole('button',{name:'Nhóm câu hỏi'}).click();await page.getByRole('button',{name:'Preview nhóm'}).nth(1).click();await page.locator('.preview-shell').waitFor();if(!page.url().includes('group=1'))throw Error('Published group preview did not select group');await page.goto(publishedUrl);await page.getByRole('button',{name:'Tạo bản nháp để sửa'}).click();await page.locator('.status.draft').waitFor();if(!await page.getByRole('button',{name:'Lưu',exact:true}).count())throw Error('Duplicate draft lacks Save');await page.getByRole('button',{name:'Thông tin',exact:true}).click();if(!(await page.getByLabel('Slug').inputValue()).startsWith('community-gardens-v'))throw Error('Duplicate exercise missing');console.log('PASS published passage: read-only → preview → duplicate passage and exercise drafts');
}finally{await browser.close()}
