import express,{type Request,type Response,type NextFunction} from 'express';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import Ajv2020 from 'ajv/dist/2020.js';
import sanitizeHtml from 'sanitize-html';
import {z} from 'zod';
import {db,dbPath,json,parse,transaction} from './db';
import {makePassage,uid,type Passage,type AnswerKey,type Issue} from '../shared/reading';
import {businessValidate} from '../shared/validate';
import {gradeSubmission} from '../shared/grading';
import {importPdfWithPython,type ImportKind} from './ai/python-bridge';

const here=dirname(fileURLToPath(import.meta.url));
// Publish validation uses the same schema that defines the two diagram answer placements.
const schema=JSON.parse(readFileSync(join(here,'..','docs','reading-ui','reading.schema.json'),'utf8'));
const ajv=new Ajv2020({allErrors:true,strict:false});ajv.addSchema(schema,'reading');
const shape=(ref:string,value:unknown):Issue[]=>{const validate=ajv.getSchema(`reading#/$defs/${ref}`)!;validate(value);return (validate.errors??[]).map(e=>({path:(e.instancePath||'/').replaceAll('/','.'),message:e.message??'Schema error'}));};
const adminToken=process.env.READING_ADMIN_TOKEN?.trim();
if(!adminToken)throw new Error('Thiếu READING_ADMIN_TOKEN trong .env');
const app=express();app.disable('x-powered-by');app.use(express.json({limit:'2mb'}));
app.use((req,res,next)=>{res.setHeader('Cache-Control','no-store');next();});
const admin=(req:Request,res:Response,next:NextFunction)=>{if(req.headers['x-admin-token']!==adminToken){res.status(401).json({error:'Admin token required'});return;}next();};
app.use('/api/admin',admin);
const body=z.object({revision:z.number().int().positive().optional()}).passthrough();
const submittedAnswers=z.record(z.string(),z.string().max(500));
const fail=(res:Response,status:number,error:string,issues?:Issue[])=>res.status(status).json({error,issues});
type DbRow=Record<string,string|number|null>;
const row=(sql:string,...args:(string|number|null)[])=>db.prepare(sql).get(...args) as DbRow|undefined;
const rows=(sql:string,...args:(string|number|null)[])=>db.prepare(sql).all(...args) as DbRow[];
const passage=(id:string)=>row('SELECT * FROM passage_versions WHERE id=?',id);
const passagePayload=(r:DbRow)=>({id:r.id,passageId:r.passage_id,status:r.status,revision:r.revision,versionNo:r.version_no,content:parse<Passage>(r.content_json),answerKey:parse<AnswerKey>(r.answer_key_json)});
const passageIssues=(r:DbRow,start?:number)=>{const p=parse<Passage>(r.content_json),k=parse<AnswerKey>(r.answer_key_json);const schemaIssues=[...shape('passageVersion',p),...shape('answerKey',k)];if(schemaIssues.length)return schemaIssues;const issues=businessValidate(p,k,start??p.questionGroups[0]?.questions[0]?.number??1);p.questionGroups.forEach((g,i)=>{if(g.content.kind==='diagram'&&g.content.assetId&&!row('SELECT id FROM media_assets WHERE id=?',g.content.assetId))issues.push({path:`questionGroups[${i}].content.assetId`,message:'Asset không tồn tại'});});return issues;};
const exercisePayload=(r:DbRow)=>({...r,topicIds:rows('SELECT topic_id FROM exercise_topics WHERE exercise_id=?',r.id).map(x=>x.topic_id),passage:passage(String(r.passage_version_id))?passagePayload(passage(String(r.passage_version_id))!):null});
const testPayload=(r:DbRow)=>({...r,testPassages:rows('SELECT order_no,passage_version_id FROM test_passages WHERE test_id=? ORDER BY order_no',r.id).map(x=>({order:x.order_no,passageVersionId:x.passage_version_id,passage:passagePayload(passage(String(x.passage_version_id))!)}))});

app.post('/api/admin/ai/import-pdf',express.raw({type:'application/pdf',limit:'15mb'}),async(req,res)=>{
 if(!process.env.GEMINI_API_KEY?.trim())return fail(res,503,'Chưa có GEMINI_API_KEY trong .env. Hãy điền key Google AI Studio và khởi động lại server.');
 const pdf=req.body as Buffer;
 if(!Buffer.isBuffer(pdf)||pdf.length<20||!pdf.subarray(0,5).equals(Buffer.from('%PDF-')))return fail(res,400,'File không phải PDF hợp lệ');
 const expectedKind=String(req.headers['x-import-kind']||'') as ImportKind;
 if(!['single_passage_bundle','full_test_bundle'].includes(expectedKind))return fail(res,400,'Thiếu loại import PDF: 1 passage hoặc full test');
 let filename='reading.pdf';try{filename=decodeURIComponent(String(req.headers['x-file-name']||filename));}catch{return fail(res,400,'Tên file không hợp lệ')}
 try{
  res.status(201).json(await importPdfWithPython(pdf,filename,dbPath,expectedKind));
 }catch(e){
  const message=e instanceof Error?e.message:'PDF import failed';
  const status=Number((e as {status?:number}).status)||500;
  fail(res,status,message);
 }
});

app.get('/api/admin/topics',(_req,res)=>res.json(rows('SELECT * FROM topics ORDER BY name')));
app.post('/api/admin/topics',(req,res)=>{const parsed=z.object({slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),name:z.string().min(1),description:z.string().default('')}).safeParse(req.body);if(!parsed.success)return fail(res,400,'Invalid topic');try{const id=uid('topic');db.prepare('INSERT INTO topics(id,slug,name,description) VALUES(?,?,?,?)').run(id,parsed.data.slug,parsed.data.name,parsed.data.description);res.status(201).json({id,...parsed.data});}catch{return fail(res,409,'Topic slug exists');}});
app.get('/api/admin/passages',(_req,res)=>res.json(rows('SELECT id,passage_id,version_no,status,revision,updated_at FROM passage_versions ORDER BY updated_at DESC')));
app.post('/api/admin/passages',(_req,res)=>{const d=makePassage(),id=d.content.passageVersionId,passageId=uid('p');transaction(()=>{db.prepare('INSERT INTO passages(id) VALUES(?)').run(passageId);db.prepare('INSERT INTO passage_versions(id,passage_id,version_no,status,content_json,answer_key_json) VALUES(?,?,1,\'draft\',?,?)').run(id,passageId,json(d.content),json(d.answerKey));});res.status(201).json(passagePayload(passage(id)!));});
app.get('/api/admin/passages/:id/draft',(req,res)=>{const r=passage(req.params.id as string);return r?res.json(passagePayload(r)):fail(res,404,'Passage not found');});
app.patch('/api/admin/passages/:id/draft',(req,res)=>{const parsed=body.safeParse(req.body);if(!parsed.success)return fail(res,400,'Invalid body');const r=passage(req.params.id as string);if(!r)return fail(res,404,'Passage not found');if(r.status!=='draft')return fail(res,409,'Published version is immutable');if(parsed.data.revision!==r.revision)return fail(res,409,'Revision conflict');const content=parsed.data.content as Passage;const answerKey=parsed.data.answerKey as AnswerKey;if(!content||!answerKey||content.passageVersionId!==r.id||answerKey.passageVersionId!==r.id)return fail(res,400,'Passage ID mismatch');db.prepare('UPDATE passage_versions SET content_json=?,answer_key_json=?,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(json(content),json(answerKey),r.id);res.json(passagePayload(passage(String(r.id))!));});
app.post('/api/admin/passages/:id/validate',(req,res)=>{const r=passage(req.params.id as string);return r?res.json({valid:passageIssues(r).length===0,issues:passageIssues(r)}):fail(res,404,'Passage not found');});
app.post('/api/admin/passages/:id/publish',(req,res)=>{const r=passage(req.params.id as string);if(!r)return fail(res,404,'Passage not found');if(r.status!=='draft')return fail(res,409,'Already published');const issues=passageIssues(r);if(issues.length)return fail(res,400,'Validation failed',issues);db.prepare("UPDATE passage_versions SET status='published',published_at=CURRENT_TIMESTAMP WHERE id=?").run(r.id);res.json(passagePayload(passage(String(r.id))!));});
app.post('/api/admin/passages/:id/duplicate',(req,res)=>{const r=passage(req.params.id as string);if(!r)return fail(res,404,'Passage not found');const old=passagePayload(r);const id=uid('pv');const p={...old.content,passageVersionId:id};const k={...old.answerKey,passageVersionId:id};const version=Number(row('SELECT MAX(version_no) AS n FROM passage_versions WHERE passage_id=?',r.passage_id)?.n??0)+1;db.prepare("INSERT INTO passage_versions(id,passage_id,version_no,status,content_json,answer_key_json) VALUES(?,?,?,'draft',?,?)").run(id,r.passage_id,version,json(p),json(k));res.status(201).json(passagePayload(passage(id)!));});
app.get('/api/admin/passages/:id/preview',(req,res)=>{const r=passage(req.params.id as string);return r?res.json(passagePayload(r)):fail(res,404,'Passage not found');});
app.post('/api/admin/passages/:id/grade',(req,res)=>{const r=passage(req.params.id as string);if(!r)return fail(res,404,'Passage not found');const input=submittedAnswers.safeParse(req.body?.answers);if(!input.success)return fail(res,400,'Invalid answers');const content=parse<Passage>(r.content_json),key=parse<AnswerKey>(r.answer_key_json);res.json({review:true,grade:gradeSubmission([content],[key],input.data),answerKeys:[key]});});
app.get('/api/admin/passages/:id/export',(req,res)=>{const r=passage(req.params.id as string);return r?res.json({schemaVersion:1,...passagePayload(r)}):fail(res,404,'Passage not found');});
app.post('/api/admin/passages/import',(req,res)=>{const p=req.body?.content as Passage,k=req.body?.answerKey as AnswerKey;if(!p||!k)return fail(res,400,'Missing content/key');const id=uid('pv'),passageId=uid('p');p.passageVersionId=id;k.passageVersionId=id;transaction(()=>{db.prepare('INSERT INTO passages(id) VALUES(?)').run(passageId);db.prepare("INSERT INTO passage_versions(id,passage_id,version_no,status,content_json,answer_key_json) VALUES(?,?,1,'draft',?,?)").run(id,passageId,json(p),json(k));});res.status(201).json(passagePayload(passage(id)!));});
app.post('/api/admin/assets',express.raw({type:'image/svg+xml',limit:'5mb'}),(req,res,next)=>{if(req.headers['content-type']!=='image/svg+xml')return next();const buf=req.body as Buffer;if(!Buffer.isBuffer(buf)||!buf.length)return fail(res,400,'Empty SVG');const clean=sanitizeHtml(buf.toString('utf8'),{allowedTags:['svg','g','path','rect','circle','ellipse','line','polyline','polygon','text','tspan','defs','marker','linearGradient','stop'],allowedAttributes:{'*':['id','x','y','x1','x2','y1','y2','width','height','viewBox','xmlns','fill','stroke','stroke-width','stroke-linecap','stroke-linejoin','font-size','font-family','font-weight','text-anchor','d','cx','cy','r','rx','ry','points','transform','opacity','offset','stop-color','marker-end']},parser:{lowerCaseTags:false,lowerCaseAttributeNames:false}});if(!clean.includes('<svg'))return fail(res,400,'Invalid SVG');const id=uid('asset');const dir=join(here,'..','uploads');mkdirSync(dir,{recursive:true});writeFileSync(join(dir,`${id}.svg`),clean);db.prepare('INSERT INTO media_assets(id,path,mime) VALUES(?,?,?)').run(id,`${id}.svg`,'image/svg+xml');res.status(201).json({id,url:`/api/assets/${id}`});});
app.post('/api/admin/assets',express.raw({type:['image/png','image/jpeg'],limit:'5mb'}),(req,res)=>{const mime=req.headers['content-type'];const buf=req.body as Buffer;if(!Buffer.isBuffer(buf)||!buf.length||!['image/png','image/jpeg'].includes(String(mime)))return fail(res,400,'Only SVG/PNG/JPEG up to 5MB');const png=buf.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));const jpg=buf[0]===255&&buf[1]===216;if((mime==='image/png'&&!png)||(mime==='image/jpeg'&&!jpg))return fail(res,400,'Image signature mismatch');const id=uid('asset'),ext=png?'png':'jpg';const dir=join(here,'..','uploads');mkdirSync(dir,{recursive:true});writeFileSync(join(dir,`${id}.${ext}`),buf);db.prepare('INSERT INTO media_assets(id,path,mime) VALUES(?,?,?)').run(id,`${id}.${ext}`,String(mime));res.status(201).json({id,url:`/api/assets/${id}`});});
app.get('/api/assets/:id',(req,res)=>{const a=row('SELECT path,mime FROM media_assets WHERE id=?',req.params.id);if(!a)return fail(res,404,'Asset not found');res.setHeader('X-Content-Type-Options','nosniff');if(a.mime==='image/svg+xml')res.setHeader('Content-Security-Policy',"default-src 'none'; style-src 'unsafe-inline'; sandbox");return res.sendFile(join(here,'..','uploads',String(a.path)));});

app.get('/api/admin/exercises',(_req,res)=>res.json(rows('SELECT * FROM single_passage_exercises ORDER BY updated_at DESC').map(exercisePayload)));
app.post('/api/admin/exercises',(req,res)=>{const p=z.object({title:z.string().default(''),description:z.string().default(''),slug:z.string().min(1),passageVersionId:z.string(),topicIds:z.array(z.string()).default([])}).safeParse(req.body);if(!p.success)return fail(res,400,'Invalid exercise');if(!passage(p.data.passageVersionId))return fail(res,400,'Passage not found');try{const id=uid('ex');transaction(()=>{db.prepare("INSERT INTO single_passage_exercises(id,slug,title,description,passage_version_id,status) VALUES(?,?,?,?,?,'draft')").run(id,p.data.slug,p.data.title,p.data.description,p.data.passageVersionId);for(const t of p.data.topicIds)db.prepare('INSERT INTO exercise_topics VALUES(?,?)').run(id,t);});res.status(201).json(exercisePayload(row('SELECT * FROM single_passage_exercises WHERE id=?',id)!));}catch{return fail(res,409,'Slug or topic invalid');}});
app.get('/api/admin/exercises/:id',(req,res)=>{const r=row('SELECT * FROM single_passage_exercises WHERE id=?',req.params.id);return r?res.json(exercisePayload(r)):fail(res,404,'Exercise not found');});
app.patch('/api/admin/exercises/:id',(req,res)=>{const r=row('SELECT * FROM single_passage_exercises WHERE id=?',req.params.id);if(!r)return fail(res,404,'Exercise not found');if(r.status!=='draft')return fail(res,409,'Published exercise immutable');if(req.body.revision!==r.revision)return fail(res,409,'Revision conflict');const p=z.object({title:z.string(),description:z.string(),slug:z.string().min(1),passageVersionId:z.string(),topicIds:z.array(z.string())}).safeParse(req.body);if(!p.success||!passage(p.data.passageVersionId))return fail(res,400,'Invalid exercise');try{transaction(()=>{db.prepare('UPDATE single_passage_exercises SET slug=?,title=?,description=?,passage_version_id=?,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(p.data.slug,p.data.title,p.data.description,p.data.passageVersionId,r.id);db.prepare('DELETE FROM exercise_topics WHERE exercise_id=?').run(r.id);for(const t of p.data.topicIds)db.prepare('INSERT INTO exercise_topics VALUES(?,?)').run(r.id,t);});res.json(exercisePayload(row('SELECT * FROM single_passage_exercises WHERE id=?',r.id)!));}catch{return fail(res,409,'Slug/topic conflict');}});
app.post('/api/admin/exercises/:id/validate',(req,res)=>{const r=row('SELECT * FROM single_passage_exercises WHERE id=?',req.params.id);if(!r)return fail(res,404,'Exercise not found');const p=passage(String(r.passage_version_id));const doc={schemaVersion:1,id:r.id,slug:r.slug,title:r.title,description:r.description,passageVersionId:r.passage_version_id,topicIds:rows('SELECT topic_id FROM exercise_topics WHERE exercise_id=?',r.id).map(x=>x.topic_id),status:r.status};const issues=[...shape('singlePassageExercise',doc),...(p?passageIssues(p):[{path:'passageVersionId',message:'Passage missing'}])];if(!String(r.description).trim())issues.push({path:'description',message:'Cần mô tả'});res.json({valid:issues.length===0,issues});});
app.post('/api/admin/exercises/:id/publish',(req,res)=>{const r=row('SELECT * FROM single_passage_exercises WHERE id=?',req.params.id);if(!r)return fail(res,404,'Exercise not found');if(r.status!=='draft')return fail(res,409,'Already published or archived');const p=passage(String(r.passage_version_id));if(!p)return fail(res,400,'Passage missing');const doc={schemaVersion:1,id:r.id,slug:r.slug,title:r.title,description:r.description,passageVersionId:r.passage_version_id,topicIds:rows('SELECT topic_id FROM exercise_topics WHERE exercise_id=?',r.id).map(x=>x.topic_id),status:r.status};const issues=[...shape('singlePassageExercise',doc),...passageIssues(p)];if(!String(r.title).trim())issues.push({path:'title',message:'Cần tiêu đề'});if(!String(r.description).trim())issues.push({path:'description',message:'Cần mô tả'});if(issues.length)return fail(res,400,'Validation failed',issues);transaction(()=>{if(p.status==='draft')db.prepare("UPDATE passage_versions SET status='published',published_at=CURRENT_TIMESTAMP WHERE id=?").run(p.id);db.prepare("UPDATE single_passage_exercises SET status='published',published_at=CURRENT_TIMESTAMP WHERE id=?").run(r.id);});res.json(exercisePayload(row('SELECT * FROM single_passage_exercises WHERE id=?',r.id)!));});
app.post('/api/admin/exercises/:id/archive',(req,res)=>{db.prepare("UPDATE single_passage_exercises SET status='archived' WHERE id=?").run(req.params.id);res.json({ok:true});});

app.get('/api/admin/tests',(_req,res)=>res.json(rows('SELECT * FROM full_reading_tests ORDER BY updated_at DESC').map(testPayload)));
app.post('/api/admin/tests',(req,res)=>{const p=z.object({slug:z.string().min(1),title:z.string().default(''),description:z.string().default(''),timeLimitMinutes:z.number().int().positive().default(60),passageVersionIds:z.array(z.string()).max(3).default([])}).safeParse(req.body);if(!p.success)return fail(res,400,'Invalid test');try{const id=uid('test');transaction(()=>{db.prepare("INSERT INTO full_reading_tests(id,slug,title,description,time_limit_minutes,status) VALUES(?,?,?,?,?,'draft')").run(id,p.data.slug,p.data.title,p.data.description,p.data.timeLimitMinutes);p.data.passageVersionIds.forEach((v,i)=>db.prepare('INSERT INTO test_passages VALUES(?,?,?)').run(id,i+1,v));});res.status(201).json(testPayload(row('SELECT * FROM full_reading_tests WHERE id=?',id)!));}catch{return fail(res,409,'Slug or passage invalid');}});
app.get('/api/admin/tests/:id',(req,res)=>{const r=row('SELECT * FROM full_reading_tests WHERE id=?',req.params.id);return r?res.json(testPayload(r)):fail(res,404,'Test not found');});
app.post('/api/admin/tests/:id/grade',(req,res)=>{const r=row('SELECT * FROM full_reading_tests WHERE id=?',req.params.id);if(!r)return fail(res,404,'Test not found');const input=submittedAnswers.safeParse(req.body?.answers);if(!input.success)return fail(res,400,'Invalid answers');const parts=rows('SELECT passage_version_id FROM test_passages WHERE test_id=? ORDER BY order_no',r.id).map(x=>passage(String(x.passage_version_id))!);const passages=parts.map(x=>parse<Passage>(x.content_json)),keys=parts.map(x=>parse<AnswerKey>(x.answer_key_json));res.json({review:true,grade:gradeSubmission(passages,keys,input.data),answerKeys:keys});});
app.patch('/api/admin/tests/:id',(req,res)=>{const r=row('SELECT * FROM full_reading_tests WHERE id=?',req.params.id);if(!r)return fail(res,404,'Test not found');if(r.status!=='draft')return fail(res,409,'Published test immutable');if(req.body.revision!==r.revision)return fail(res,409,'Revision conflict');const p=z.object({slug:z.string().min(1),title:z.string(),description:z.string(),timeLimitMinutes:z.number().int().positive(),passageVersionIds:z.array(z.string()).max(3)}).safeParse(req.body);if(!p.success)return fail(res,400,'Invalid test');try{transaction(()=>{db.prepare('UPDATE full_reading_tests SET slug=?,title=?,description=?,time_limit_minutes=?,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(p.data.slug,p.data.title,p.data.description,p.data.timeLimitMinutes,r.id);db.prepare('DELETE FROM test_passages WHERE test_id=?').run(r.id);p.data.passageVersionIds.forEach((v,i)=>db.prepare('INSERT INTO test_passages VALUES(?,?,?)').run(r.id,i+1,v));});res.json(testPayload(row('SELECT * FROM full_reading_tests WHERE id=?',r.id)!));}catch{return fail(res,409,'Slug or passage invalid');}});
const testIssues=(r:DbRow):Issue[]=>{const t=testPayload(r),parts=t.testPassages as {order:number;passageVersionId:string;passage:ReturnType<typeof passagePayload>}[];const doc={schemaVersion:1,id:r.id,slug:r.slug,title:r.title,description:r.description,timeLimitMinutes:r.time_limit_minutes,testPassages:parts.map(x=>({order:x.order,passageVersionId:x.passageVersionId})),status:r.status};const issues=shape('fullReadingTest',doc);if(!String(r.description).trim())issues.push({path:'description',message:'Cần mô tả'});if(parts.length!==3)issues.push({path:'testPassages',message:'Cần đúng 3 passages'});let next=1;parts.forEach((part,i)=>{const p=part.passage.content;issues.push(...passageIssues(passage(part.passageVersionId)!,next).map(x=>({path:`testPassages[${i}].${x.path}`,message:x.message})));next+=p.questionGroups.flatMap(g=>g.questions).length;});if(new Set(parts.map(x=>x.passageVersionId)).size!==parts.length)issues.push({path:'testPassages',message:'Passages phải khác nhau'});return issues;};
app.post('/api/admin/tests/:id/validate',(req,res)=>{const r=row('SELECT * FROM full_reading_tests WHERE id=?',req.params.id);return r?res.json({valid:testIssues(r).length===0,issues:testIssues(r)}):fail(res,404,'Test not found');});
app.post('/api/admin/tests/:id/publish',(req,res)=>{const r=row('SELECT * FROM full_reading_tests WHERE id=?',req.params.id);if(!r)return fail(res,404,'Test not found');if(r.status!=='draft')return fail(res,409,'Already published or archived');const issues=testIssues(r);if(issues.length)return fail(res,400,'Validation failed',issues);transaction(()=>{for(const x of rows('SELECT passage_version_id FROM test_passages WHERE test_id=?',r.id))db.prepare("UPDATE passage_versions SET status='published',published_at=COALESCE(published_at,CURRENT_TIMESTAMP) WHERE id=?").run(x.passage_version_id);db.prepare("UPDATE full_reading_tests SET status='published',published_at=CURRENT_TIMESTAMP WHERE id=?").run(r.id);});res.json(testPayload(row('SELECT * FROM full_reading_tests WHERE id=?',r.id)!));});
app.post('/api/admin/tests/:id/archive',(req,res)=>{db.prepare("UPDATE full_reading_tests SET status='archived' WHERE id=?").run(req.params.id);res.json({ok:true});});

app.get('/api/reading/topics',(_req,res)=>res.json(rows('SELECT * FROM topics ORDER BY name')));
app.get('/api/reading/exercises',(req,res)=>{const q=String(req.query.q??''),topics=String(req.query.topic??'').split(',').filter(Boolean),page=Math.max(1,Number(req.query.page)||1),limit=12;let sql="SELECT e.id,e.slug,e.title,e.description,e.published_at FROM single_passage_exercises e WHERE e.status='published' AND (e.title LIKE ? OR e.description LIKE ?)";const args:(string|number|null)[]=[`%${q}%`,`%${q}%`];for(const topic of topics){sql+=' AND EXISTS (SELECT 1 FROM exercise_topics et JOIN topics t ON et.topic_id=t.id WHERE et.exercise_id=e.id AND t.slug=?)';args.push(topic);}const total=Number(row(`SELECT COUNT(*) AS n FROM (${sql})`,...args)?.n??0);res.json({items:rows(sql+' ORDER BY e.published_at DESC LIMIT ? OFFSET ?',...args,limit,(page-1)*limit),page,total,pages:Math.ceil(total/limit)});});
app.get('/api/reading/exercises/:slug',(req,res)=>{const r=row("SELECT * FROM single_passage_exercises WHERE slug=? AND status='published'",req.params.slug);if(!r)return fail(res,404,'Exercise not found');const p=passage(String(r.passage_version_id));if(!p||p.status!=='published')return fail(res,404,'Passage unavailable');res.json({schemaVersion:1,id:r.id,slug:r.slug,title:r.title,description:r.description,topicIds:rows('SELECT topic_id FROM exercise_topics WHERE exercise_id=?',r.id).map(x=>x.topic_id),passage:parse<Passage>(p.content_json)});});
app.get('/api/reading/tests/:slug',(req,res)=>{const r=row("SELECT * FROM full_reading_tests WHERE slug=? AND status='published'",req.params.slug);if(!r)return fail(res,404,'Test not found');res.json({schemaVersion:1,id:r.id,slug:r.slug,title:r.title,description:r.description,timeLimitMinutes:r.time_limit_minutes,testPassages:rows('SELECT order_no,passage_version_id FROM test_passages WHERE test_id=? ORDER BY order_no',r.id).map(x=>({order:x.order_no,passage:parse<Passage>(passage(String(x.passage_version_id))!.content_json)}))});});
app.post('/api/reading/exercises/:slug/submit',(req,res)=>{const r=row("SELECT passage_version_id FROM single_passage_exercises WHERE slug=? AND status='published'",req.params.slug);if(!r)return fail(res,404,'Exercise not found');const p=passage(String(r.passage_version_id));if(!p)return fail(res,404,'Passage unavailable');const input=submittedAnswers.safeParse(req.body?.answers);if(!input.success)return fail(res,400,'Invalid answers');const content=parse<Passage>(p.content_json),key=parse<AnswerKey>(p.answer_key_json);res.json({review:true,grade:gradeSubmission([content],[key],input.data),answerKeys:[key]});});
app.post('/api/reading/tests/:slug/submit',(req,res)=>{const r=row("SELECT id FROM full_reading_tests WHERE slug=? AND status='published'",req.params.slug);if(!r)return fail(res,404,'Test not found');const input=submittedAnswers.safeParse(req.body?.answers);if(!input.success)return fail(res,400,'Invalid answers');const parts=rows('SELECT passage_version_id FROM test_passages WHERE test_id=? ORDER BY order_no',r.id).map(x=>passage(String(x.passage_version_id))!);const passages=parts.map(x=>parse<Passage>(x.content_json)),keys=parts.map(x=>parse<AnswerKey>(x.answer_key_json));res.json({review:true,grade:gradeSubmission(passages,keys,input.data),answerKeys:keys});});
app.use((err:Error,_req:Request,res:Response,_next:NextFunction)=>{console.error(err);res.status(500).json({error:'Internal server error'});});
const port=Number(process.env.PORT??3001);app.listen(port,'127.0.0.1',()=>console.log(`Reading API http://127.0.0.1:${port}`));
