import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{BrowserRouter,Link,Route,Routes}from'react-router-dom';
import{AdminGate,Dashboard,PassageEditorPage,TestEditorPage}from'./Admin';
import{PreviewRoute,PublicPreviewRoute}from'./Preview';
import{api}from'./api';
import'./style.css';
type Item={id:string;slug:string;title:string;description:string};type Topic={id:string;slug:string;name:string};
function PublicList(){const[items,setItems]=useState<Item[]>([]),[topics,setTopics]=useState<Topic[]>([]),[selected,setSelected]=useState<string[]>(()=>new URLSearchParams(location.search).get('topic')?.split(',').filter(Boolean)||[]),[query,setQuery]=useState(()=>new URLSearchParams(location.search).get('q')||''),[page,setPage]=useState(()=>Math.max(1,Number(new URLSearchParams(location.search).get('page'))||1)),[pages,setPages]=useState(1);useEffect(()=>{api<Topic[]>('/reading/topics').then(setTopics)},[]);useEffect(()=>{const params=new URLSearchParams({q:query,topic:selected.join(','),page:String(page)});if(location.pathname==='/reading/passages')history.replaceState(null,'',`/reading/passages?${params}`);api<{items:Item[];pages:number}>(`/reading/exercises?${params}`).then(x=>{setItems(x.items);setPages(x.pages)})},[selected,query,page]);return <div className="public-page"><header className="admin-header"><Link className="brand" to="/reading/passages">IELTS <strong>space</strong><sup>★</sup></Link><Link to="/admin/reading">Admin ↗</Link></header><main className="public-list"><span className="eyebrow">READING PRACTICE</span><h1>Bài đọc 1 passage</h1><p>Chọn chủ đề và tìm bài đã xuất bản.</p><input aria-label="Tìm bài" placeholder="Tìm theo tiêu đề hoặc mô tả" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/><div className="topic-filters">{topics.map(t=><button key={t.id} className={selected.includes(t.slug)?'active':''} onClick={()=>{setSelected(x=>x.includes(t.slug)?x.filter(v=>v!==t.slug):[...x,t.slug]);setPage(1)}}>{t.name}</button>)}</div><div className="dashboard-grid">{items.map(x=><Link className="dashboard-card" key={x.id} to={`/reading/preview/passage/${x.slug}`}><h2>{x.title}</h2><p>{x.description}</p><span>Bắt đầu ↗</span></Link>)}</div><div className="inline"><button disabled={page<=1} onClick={()=>setPage(x=>x-1)}>Trước</button><span>Trang {page}/{Math.max(1,pages)}</span><button disabled={page>=pages} onClick={()=>setPage(x=>x+1)}>Sau</button></div></main></div>}
function App(){return <BrowserRouter><Routes><Route path="/" element={<PublicList/>}/><Route path="/reading/passages" element={<PublicList/>}/><Route path="/reading/preview/:kind/:slug" element={<PublicPreviewRoute/>}/><Route path="/admin/reading" element={<AdminGate><Dashboard/></AdminGate>}/><Route path="/admin/reading/passages/:id/edit" element={<AdminGate><PassageEditorPage/></AdminGate>}/><Route path="/admin/reading/tests/:id/edit" element={<AdminGate><TestEditorPage/></AdminGate>}/><Route path="/admin/reading/preview/:kind/:id" element={<AdminGate><PreviewRoute/></AdminGate>}/></Routes></BrowserRouter>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
