import {useEffect,useRef,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import type {AnswerKey,Passage} from '../shared/reading';
import {heading} from '../shared/reading';
import type {GradeResult} from '../shared/grading';
import {questionTypeRegistry} from './registry';
import {api,post} from './api';
import {RichText} from './RichText';
import {plainReadingText} from '../shared/richText';
type SubmitResult={answerKeys:AnswerKey[];grade:GradeResult};
type PreviewData={passages:Passage[];keys?:AnswerKey[];title:string;timeLimitMinutes?:number;admin?:boolean;onSubmit?:(answers:Record<string,string>)=>Promise<SubmitResult>};
const ExitIcon=()=> <svg className="action-icon" aria-hidden="true" width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M10 5H6.8A1.8 1.8 0 0 0 5 6.8v10.4A1.8 1.8 0 0 0 6.8 19H10M14.5 8.5 18 12l-3.5 3.5M9 12h9" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>;
const SubmitIcon=()=> <svg className="action-icon" aria-hidden="true" width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="m20 4-7.2 16-2.2-6.6L4 11.2 20 4Z" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/><path d="m10.8 13.2 4-4" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/></svg>;
export function ReadingPreview({passages,keys:initialKeys,title,timeLimitMinutes=60,admin=false,onSubmit}:PreviewData){
 const storageKey=`reading-attempt:${passages.map(p=>p.passageVersionId).join(':')}`;const readSaved=<T,>(field:string,fallback:T):T=>{try{return JSON.parse(sessionStorage.getItem(`${storageKey}:${field}`)||'null')??fallback}catch{return fallback}};
 const params=new URLSearchParams(location.search);const initialPassage=Math.min(passages.length-1,Math.max(0,Number(params.get('passage'))||0));const [keys,setKeys]=useState(initialKeys),[grade,setGrade]=useState<GradeResult|null>(null),[submitting,setSubmitting]=useState(false),[submitError,setSubmitError]=useState(''),[passageIndex,setPassageIndex]=useState(initialPassage),[groupByPassage,setGroupByPassage]=useState<Record<number,number>>({[initialPassage]:Math.max(0,Number(params.get('group'))||0)}),[answers,setAnswers]=useState<Record<string,string>>(()=>readSaved('answers',{})),[bookmarks,setBookmarks]=useState<Record<string,boolean>>(()=>readSaved('bookmarks',{})),[activeQuestion,setActiveQuestion]=useState(params.get('question')||''),[evidence,setEvidence]=useState(''),[evidenceQuote,setEvidenceQuote]=useState(''),[highlight,setHighlight]=useState<{blockId:string;quote:string}|null>(null),[hint,setHint]=useState(false),[textSize,setTextSize]=useState(17),[mobileTab,setMobileTab]=useState<'passage'|'questions'>('passage'),[elapsedSeconds,setElapsedSeconds]=useState(0),[split,setSplit]=useState(()=>{try{return Math.min(72,Math.max(28,Number(localStorage.getItem('reading-preview-split'))||50))}catch{return 50}}),[resizing,setResizing]=useState(false);
 const leftRef=useRef<HTMLDivElement>(null),mainRef=useRef<HTMLElement>(null),splitRef=useRef(split);const p=passages[passageIndex];const groupIndex=groupByPassage[passageIndex]??0;const g=p?.questionGroups[groupIndex];const key=keys?.[passageIndex];const allQs=passages.flatMap((v,pi)=>v.questionGroups.flatMap((x,gi)=>x.questions.map(q=>({q,pi,gi}))));
 useEffect(()=>{const t=setInterval(()=>setElapsedSeconds(x=>x+1),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{sessionStorage.setItem(`${storageKey}:answers`,JSON.stringify(answers));sessionStorage.setItem(`${storageKey}:bookmarks`,JSON.stringify(bookmarks))},[answers,bookmarks,storageKey]);
 useEffect(()=>{if(activeQuestion)document.querySelector(`[data-question="${activeQuestion}"]`)?.scrollIntoView({block:'center',behavior:'smooth'})},[activeQuestion,groupIndex,passageIndex]);
 const selectQuestion=(id:string)=>{const match=allQs.find(x=>x.q.id===id);if(!match)return;setPassageIndex(match.pi);setGroupByPassage(v=>({...v,[match.pi]:match.gi}));setActiveQuestion(id);setMobileTab('questions')};
 const setSplitValue=(value:number)=>{const next=Math.min(72,Math.max(28,value));splitRef.current=next;setSplit(next)};
 const resizeTo=(clientX:number)=>{const rect=mainRef.current?.getBoundingClientRect();if(!rect)return;const innerLeft=rect.left+22,innerWidth=Math.max(1,rect.width-60);setSplitValue(((clientX-innerLeft)/innerWidth)*100)};
 const finishResize=()=>{setResizing(false);try{localStorage.setItem('reading-preview-split',String(splitRef.current))}catch{}};
 const showEvidence=(id:string)=>{const answer=key?.answers.find(a=>a.questionId===id),e=answer?.evidence[0];if(!e)return;setEvidence(e.blockId);setEvidenceQuote(plainReadingText(e.quote));setMobileTab('passage');setTimeout(()=>leftRef.current?.querySelector(`[data-block="${e.blockId}"]`)?.scrollIntoView({block:'center',behavior:'smooth'}),60)};

 const highlightSelection=()=>{const selection=window.getSelection();const quote=selection?.toString().trim();const node=selection?.anchorNode;const block=(node?.nodeType===Node.ELEMENT_NODE?node as Element:node?.parentElement)?.closest('[data-block]');if(!quote||!block||!leftRef.current?.contains(block)){setHint(true);return}const blockId=block.getAttribute('data-block')||'';const text=plainReadingText(p.sections.flatMap(s=>s.blocks).find(b=>b.id===blockId)?.text||'');if(!text.includes(quote)){setHint(true);return}setHighlight({blockId,quote});selection?.removeAllRanges()};
 const answered=allQs.filter(x=>answers[x.q.id]?.trim()).length;
 const resultById=new Map(grade?.questions.map(x=>[x.questionId,x]));
 const submit=async()=>{if(!onSubmit||submitting)return;setSubmitting(true);setSubmitError('');try{const result=await onSubmit(answers);setKeys(result.answerKeys);setGrade(result.grade)}catch(e){setSubmitError((e as Error).message)}finally{setSubmitting(false)}};
 if(!p||!g)return <div className="empty-preview">Chưa có nhóm câu hỏi để preview. <Link to="/admin/reading">Quay lại admin</Link></div>;
 const Renderer=questionTypeRegistry[g.type].Renderer;
 return <div className="preview-shell"><header className="preview-header"><div className="brand">IELTS <strong>space</strong><sup>★</sup></div><div className="breadcrumb">Reading <span>/</span> {questionTypeRegistry[g.type].label}</div><div className="header-right"><span className="practice-pill">▣ &nbsp;Chế độ luyện tập</span><span className="timer" aria-label="Thời gian còn lại">◷ &nbsp;{String(Math.floor(Math.max(0,timeLimitMinutes*60-elapsedSeconds)/60)).padStart(2,'0')}:{String(Math.max(0,timeLimitMinutes*60-elapsedSeconds)%60).padStart(2,'0')}</span><Link className="close" to={admin?'/admin/reading':'/reading/passages'}>×</Link></div></header>
 {passages.length>1&&<nav className="passage-tabs">{passages.map((x,i)=><button key={x.passageVersionId} className={i===passageIndex?'active':''} onClick={()=>{setPassageIndex(i);setMobileTab('passage')}}>Passage {i+1} · {x.questionGroups.flatMap(g=>g.questions).length} câu</button>)}</nav>}
 <div className="mobile-tabs"><button className={mobileTab==='passage'?'active':''} onClick={()=>setMobileTab('passage')}>Bài đọc</button><button className={mobileTab==='questions'?'active':''} onClick={()=>setMobileTab('questions')}>Câu hỏi</button></div>
 <main ref={mainRef} className={`preview-main has-resizer mobile-${mobileTab}`} style={{gridTemplateColumns:`minmax(0,${split}fr) 16px minmax(0,${100-split}fr)`}}><section className="passage-panel" ref={leftRef}><div className="panel-toolbar"><h2><span className="purple-icon">▤</span> Bài đọc</h2><div><button onClick={highlightSelection}>🖉 &nbsp;Highlight</button><button onClick={()=>setHint(true)}>♧ &nbsp;Lưu từ</button><button onClick={()=>setTextSize(x=>x>=21?16:x+1)}>Aa</button></div></div><div className="passage-body" style={{fontSize:textSize}}><span className="passage-label">{p.label||`READING PASSAGE ${passageIndex+1}`}</span>{p.leadIn&&<p className="lead-in"><RichText text={p.leadIn}/></p>}<h1><RichText text={p.title}/></h1>{p.description&&<p className="passage-description"><RichText text={p.description}/></p>}{p.sections.map(s=><div className="passage-section" key={s.id}><strong>{s.label}</strong><div>{s.blocks.map(b=><p className={evidence===b.id?'evidence-block':''} data-block={b.id} key={b.id}><RichText text={b.text} highlight={evidence===b.id?evidenceQuote:highlight?.blockId===b.id?highlight.quote:''}/></p>)}</div></div>)}</div></section>
 <div className={`preview-resizer ${resizing?'dragging':''}`} role="separator" aria-label="Thay đổi độ rộng bài đọc và câu hỏi" aria-orientation="vertical" aria-valuemin={28} aria-valuemax={72} aria-valuenow={Math.round(split)} tabIndex={0} onDoubleClick={()=>{setSplitValue(50);localStorage.setItem('reading-preview-split','50')}} onPointerDown={e=>{setResizing(true);e.currentTarget.setPointerCapture(e.pointerId);resizeTo(e.clientX)}} onPointerMove={e=>{if(resizing)resizeTo(e.clientX)}} onPointerUp={finishResize} onPointerCancel={finishResize} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?28:e.key==='End'?72:splitRef.current+(e.key==='ArrowLeft'?-1:1)*(e.shiftKey?5:2);setSplitValue(next);try{localStorage.setItem('reading-preview-split',String(splitRef.current))}catch{}}}><span/></div>
 <section className="question-panel"><div className="question-scroll"><div className="question-panel-head"><div className="group-switch"><h2>{heading(g)}</h2><select aria-label="Chọn nhóm" value={groupIndex} onChange={e=>setGroupByPassage(x=>({...x,[passageIndex]:Number(e.target.value)}))}>{p.questionGroups.map((x,i)=><option key={x.id} value={i}>{heading(x)} · {questionTypeRegistry[x.type].label}</option>)}</select></div>{g.instructionBlocks.filter(b=>b.kind==='instruction').map((b,i)=><p key={i} className="instruction"><RichText text={b.text}/></p>)}{g.instructionBlocks.filter(b=>b.kind==='answer_format').map((b,i)=><div className="info-strip" key={i}>ⓘ &nbsp;<RichText text={b.text}/></div>)}{g.instructionBlocks.filter(b=>b.kind==='note').map((b,i)=><div className="note-strip" key={i}><RichText text={b.text}/></div>)}{grade&&<div className="grade-banner"><strong>Kết quả: {grade.correct}/{grade.total} đúng</strong><span>{grade.incorrect} sai · {grade.unanswered} chưa trả lời</span></div>}{submitError&&<div className="error-banner">{submitError}</div>}</div><Renderer group={g} sections={p.sections.map(s=>({id:s.id,label:s.label}))} answers={answers} onAnswer={(id,value)=>setAnswers(x=>({...x,[id]:value}))} bookmarks={bookmarks} onToggleBookmark={id=>setBookmarks(x=>({...x,[id]:!x[id]}))} focusId={activeQuestion}/>{grade&&key&&<div className="review-list"><h3>Lời giải sau khi nộp</h3>{g.questions.map(q=>{const a=key.answers.find(x=>x.questionId===q.id);return <details key={q.id}><summary>Câu {q.number} · {resultById.get(q.id)?.status==='correct'?'Đúng':resultById.get(q.id)?.status==='incorrect'?'Sai':'Chưa trả lời'}</summary><p><b>Đáp án:</b> {a?.acceptedAnswers.join(', ')}</p><p>{a?.explanation}</p>{a?.evidence.length?<button onClick={()=>showEvidence(q.id)}>Xem vị trí ↗</button>:<span>Không có bằng chứng trực tiếp</span>}</details>})}</div>}</div></section></main>
 <footer className="preview-footer"><div className="save-info"><span className="green-dot"/> Đã lưu <span className="separator">|</span> {grade?`${grade.correct}/${grade.total} câu đúng`:`${answered}/${allQs.length} câu đã trả lời`}</div><div className="question-palette">{allQs.map(({q,pi})=><button key={q.id} className={`${answers[q.id]?'answered':''} ${activeQuestion===q.id?'current':''} ${resultById.get(q.id)?.status||''}`} onClick={()=>selectQuestion(q.id)} title={`Passage ${pi+1}, câu ${q.number}`}>{q.number}{bookmarks[q.id]&&<span className="bookmark-mark">★</span>}</button>)}</div><div className="footer-actions"><Link className="exit-btn" to={admin?'/admin/reading':'/reading/passages'}><ExitIcon/>Lưu & thoát</Link><button className="submit-btn" disabled={submitting} onClick={submit}><SubmitIcon/>{submitting?'Đang chấm…':grade?'Chấm lại':'Nộp bài'}</button></div></footer>{hint&&<aside className="hint-popover">Chọn một đoạn văn để Highlight. Câu trả lời và câu đã lưu chỉ nằm trong tab trình duyệt. <button onClick={()=>setHint(false)}>Đóng</button></aside>}</div>;
}
export function PreviewRoute(){const {kind,id}=useParams();const [data,setData]=useState<PreviewData|null>(null),[error,setError]=useState('');useEffect(()=>{(async()=>{try{if(kind==='passage'){const p=await api<{content:Passage;answerKey:AnswerKey}>(`/admin/passages/${id}/preview`,{},true);setData({passages:[p.content],keys:[p.answerKey],title:p.content.title,admin:true,onSubmit:answers=>post<SubmitResult>(`/admin/passages/${id}/grade`,{answers})});}else if(kind==='test'){const t=await api<{title:string;time_limit_minutes:number;testPassages:{passage:{content:Passage;answerKey:AnswerKey}}[]}>(`/admin/tests/${id}`,{},true);setData({passages:t.testPassages.map(x=>x.passage.content),keys:t.testPassages.map(x=>x.passage.answerKey),title:t.title,timeLimitMinutes:t.time_limit_minutes,admin:true,onSubmit:answers=>post<SubmitResult>(`/admin/tests/${id}/grade`,{answers})});}}catch(e){setError(String(e))}})()},[kind,id]);return data?<ReadingPreview {...data}/>:<div className="loading">{error||'Đang tải preview…'}</div>}
export function PublicPreviewRoute(){const {kind,slug}=useParams();const [data,setData]=useState<PreviewData|null>(null),[error,setError]=useState('');useEffect(()=>{(async()=>{try{if(kind==='passage'){const p=await api<{title:string;passage:Passage}>(`/reading/exercises/${slug}`);setData({passages:[p.passage],title:p.title,onSubmit:answers=>post<SubmitResult>(`/reading/exercises/${slug}/submit`,{answers},false)});}else{const t=await api<{title:string;timeLimitMinutes:number;testPassages:{passage:Passage}[]}>(`/reading/tests/${slug}`);setData({passages:t.testPassages.map(x=>x.passage),title:t.title,timeLimitMinutes:t.timeLimitMinutes,onSubmit:answers=>post<SubmitResult>(`/reading/tests/${slug}/submit`,{answers},false)});}}catch(e){setError(String(e))}})()},[kind,slug]);return data?<ReadingPreview {...data}/>:<div className="loading">{error||'Đang tải bài đọc…'}</div>}
